### ISSUE TITLE
GNOME 46 support

### ISSUE THREAD

**Issue by RedBearAK** [xremap/xremap-gnome#6]
@k0kubun 

I was able to install The Xremap GNOME extension in Fedora 40 with GNOME 46 using Extension Manager (the third-party Flatpak app), by enabling the "Show Unsupported" option in its hamburger menu. Of course it wouldn't activate. Then I modified the `metadata.json` file and added "46" to the list of supported shell versions, and logged out so that it would activate on GNOME 46. 

No errors or issues with the functionality of the extension were observed. Seems to work just as well as it did in G45. 

The beta announcement for Fedora 40 should be happening soon. It's already quite good even as a pre-beta. A lot of Fedora users are going to be upgrading to F40 long before the final release, which should be in about 60 days. Beta announcement is probably 30 days from now or less. 

I think all you need to change is the shell versions list, to add "46".

**Comment by k0kubun** [comment]
Thanks for the report. I would appreciate it if you could file a pull request next time, but I'll edit that myself now.

**Comment by k0kubun** [comment]
OK, I uploaded it. will need to wait for them to review it, but closing this issue.

**Comment by RedBearAK** [comment]
@k0kubun 

Just confirming the updated extension showing G46 support is live. Thanks for your time.
